#!/usr/bin/env bash
TEST="/home/manuel/juliachessengine/"
TEST+="uci.jl"
if [ ! -z "$1" ];
then
    if [ $1 = 'bench' ]; then
        echo $TEST
        julia -t 1 $TEST bench
    else
        julia -t 1 $TEST
    fi
else
    julia -t 2 $TEST
fi 

